package com.self.ddyoung.daily.model;

public class UserDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_100w.id
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_100w.name
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_100w.age
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    private Byte age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_100w.addr
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    private String addr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_100w.remark
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_100w.id
     *
     * @return the value of test_100w.id
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_100w.id
     *
     * @param id the value for test_100w.id
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_100w.name
     *
     * @return the value of test_100w.name
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_100w.name
     *
     * @param name the value for test_100w.name
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_100w.age
     *
     * @return the value of test_100w.age
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_100w.age
     *
     * @param age the value for test_100w.age
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_100w.addr
     *
     * @return the value of test_100w.addr
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_100w.addr
     *
     * @param addr the value for test_100w.addr
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_100w.remark
     *
     * @return the value of test_100w.remark
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_100w.remark
     *
     * @param remark the value for test_100w.remark
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}