package com.self.ddyoung.daily.model;

import java.math.BigDecimal;
import java.util.Date;

public class VerifyDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.id
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.refer_id
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String referId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.writeoff_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String writeoffNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.begin_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String beginNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.end_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String endNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.end_no_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String endNoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.end_no_bill_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String endNoBillType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.settlement_bill_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String settlementBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.end_no_id
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private Long endNoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.org_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.org_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.org_unified_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String orgUnifiedCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.end_org_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String endOrgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.end_org_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String endOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.end_unified_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String endUnifiedCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.end_source_bill_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String endSourceBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.bad_writeoff_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String badWriteoffType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.writeoff_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String writeoffType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.create_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String createType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.writeoff_amount
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private BigDecimal writeoffAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.is_sign
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String isSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.is_red_back
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String isRedBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.customer_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String customerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.customer_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.statement_bill_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String statementBillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.account_date
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private Date accountDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.writeoff_batch_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String writeoffBatchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.remark
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.create_user_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String createUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.create_user_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.modify_user_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String modifyUserCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.modify_user_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String modifyUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.active
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String active;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.is_delete
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.create_date
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.modify_date
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.is_init
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String isInit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.version_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private Long versionNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.attribute
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String attribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.option
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private Long option;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cu_ac_writeoff.customer_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    private String customerType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.id
     *
     * @return the value of cu_ac_writeoff.id
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.id
     *
     * @param id the value for cu_ac_writeoff.id
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.refer_id
     *
     * @return the value of cu_ac_writeoff.refer_id
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getReferId() {
        return referId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.refer_id
     *
     * @param referId the value for cu_ac_writeoff.refer_id
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setReferId(String referId) {
        this.referId = referId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.writeoff_no
     *
     * @return the value of cu_ac_writeoff.writeoff_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getWriteoffNo() {
        return writeoffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.writeoff_no
     *
     * @param writeoffNo the value for cu_ac_writeoff.writeoff_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setWriteoffNo(String writeoffNo) {
        this.writeoffNo = writeoffNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.begin_no
     *
     * @return the value of cu_ac_writeoff.begin_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getBeginNo() {
        return beginNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.begin_no
     *
     * @param beginNo the value for cu_ac_writeoff.begin_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setBeginNo(String beginNo) {
        this.beginNo = beginNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.end_no
     *
     * @return the value of cu_ac_writeoff.end_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getEndNo() {
        return endNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.end_no
     *
     * @param endNo the value for cu_ac_writeoff.end_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setEndNo(String endNo) {
        this.endNo = endNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.end_no_type
     *
     * @return the value of cu_ac_writeoff.end_no_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getEndNoType() {
        return endNoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.end_no_type
     *
     * @param endNoType the value for cu_ac_writeoff.end_no_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setEndNoType(String endNoType) {
        this.endNoType = endNoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.end_no_bill_type
     *
     * @return the value of cu_ac_writeoff.end_no_bill_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getEndNoBillType() {
        return endNoBillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.end_no_bill_type
     *
     * @param endNoBillType the value for cu_ac_writeoff.end_no_bill_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setEndNoBillType(String endNoBillType) {
        this.endNoBillType = endNoBillType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.settlement_bill_no
     *
     * @return the value of cu_ac_writeoff.settlement_bill_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getSettlementBillNo() {
        return settlementBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.settlement_bill_no
     *
     * @param settlementBillNo the value for cu_ac_writeoff.settlement_bill_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setSettlementBillNo(String settlementBillNo) {
        this.settlementBillNo = settlementBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.end_no_id
     *
     * @return the value of cu_ac_writeoff.end_no_id
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public Long getEndNoId() {
        return endNoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.end_no_id
     *
     * @param endNoId the value for cu_ac_writeoff.end_no_id
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setEndNoId(Long endNoId) {
        this.endNoId = endNoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.org_name
     *
     * @return the value of cu_ac_writeoff.org_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.org_name
     *
     * @param orgName the value for cu_ac_writeoff.org_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.org_code
     *
     * @return the value of cu_ac_writeoff.org_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.org_code
     *
     * @param orgCode the value for cu_ac_writeoff.org_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.org_unified_code
     *
     * @return the value of cu_ac_writeoff.org_unified_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getOrgUnifiedCode() {
        return orgUnifiedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.org_unified_code
     *
     * @param orgUnifiedCode the value for cu_ac_writeoff.org_unified_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setOrgUnifiedCode(String orgUnifiedCode) {
        this.orgUnifiedCode = orgUnifiedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.end_org_name
     *
     * @return the value of cu_ac_writeoff.end_org_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getEndOrgName() {
        return endOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.end_org_name
     *
     * @param endOrgName the value for cu_ac_writeoff.end_org_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setEndOrgName(String endOrgName) {
        this.endOrgName = endOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.end_org_code
     *
     * @return the value of cu_ac_writeoff.end_org_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getEndOrgCode() {
        return endOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.end_org_code
     *
     * @param endOrgCode the value for cu_ac_writeoff.end_org_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setEndOrgCode(String endOrgCode) {
        this.endOrgCode = endOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.end_unified_code
     *
     * @return the value of cu_ac_writeoff.end_unified_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getEndUnifiedCode() {
        return endUnifiedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.end_unified_code
     *
     * @param endUnifiedCode the value for cu_ac_writeoff.end_unified_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setEndUnifiedCode(String endUnifiedCode) {
        this.endUnifiedCode = endUnifiedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.end_source_bill_no
     *
     * @return the value of cu_ac_writeoff.end_source_bill_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getEndSourceBillNo() {
        return endSourceBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.end_source_bill_no
     *
     * @param endSourceBillNo the value for cu_ac_writeoff.end_source_bill_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setEndSourceBillNo(String endSourceBillNo) {
        this.endSourceBillNo = endSourceBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.bad_writeoff_type
     *
     * @return the value of cu_ac_writeoff.bad_writeoff_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getBadWriteoffType() {
        return badWriteoffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.bad_writeoff_type
     *
     * @param badWriteoffType the value for cu_ac_writeoff.bad_writeoff_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setBadWriteoffType(String badWriteoffType) {
        this.badWriteoffType = badWriteoffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.writeoff_type
     *
     * @return the value of cu_ac_writeoff.writeoff_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getWriteoffType() {
        return writeoffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.writeoff_type
     *
     * @param writeoffType the value for cu_ac_writeoff.writeoff_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setWriteoffType(String writeoffType) {
        this.writeoffType = writeoffType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.create_type
     *
     * @return the value of cu_ac_writeoff.create_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getCreateType() {
        return createType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.create_type
     *
     * @param createType the value for cu_ac_writeoff.create_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setCreateType(String createType) {
        this.createType = createType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.writeoff_amount
     *
     * @return the value of cu_ac_writeoff.writeoff_amount
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public BigDecimal getWriteoffAmount() {
        return writeoffAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.writeoff_amount
     *
     * @param writeoffAmount the value for cu_ac_writeoff.writeoff_amount
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setWriteoffAmount(BigDecimal writeoffAmount) {
        this.writeoffAmount = writeoffAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.is_sign
     *
     * @return the value of cu_ac_writeoff.is_sign
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getIsSign() {
        return isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.is_sign
     *
     * @param isSign the value for cu_ac_writeoff.is_sign
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setIsSign(String isSign) {
        this.isSign = isSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.is_red_back
     *
     * @return the value of cu_ac_writeoff.is_red_back
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getIsRedBack() {
        return isRedBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.is_red_back
     *
     * @param isRedBack the value for cu_ac_writeoff.is_red_back
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setIsRedBack(String isRedBack) {
        this.isRedBack = isRedBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.customer_code
     *
     * @return the value of cu_ac_writeoff.customer_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.customer_code
     *
     * @param customerCode the value for cu_ac_writeoff.customer_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.customer_name
     *
     * @return the value of cu_ac_writeoff.customer_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.customer_name
     *
     * @param customerName the value for cu_ac_writeoff.customer_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.statement_bill_no
     *
     * @return the value of cu_ac_writeoff.statement_bill_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getStatementBillNo() {
        return statementBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.statement_bill_no
     *
     * @param statementBillNo the value for cu_ac_writeoff.statement_bill_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setStatementBillNo(String statementBillNo) {
        this.statementBillNo = statementBillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.account_date
     *
     * @return the value of cu_ac_writeoff.account_date
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public Date getAccountDate() {
        return accountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.account_date
     *
     * @param accountDate the value for cu_ac_writeoff.account_date
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setAccountDate(Date accountDate) {
        this.accountDate = accountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.writeoff_batch_no
     *
     * @return the value of cu_ac_writeoff.writeoff_batch_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getWriteoffBatchNo() {
        return writeoffBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.writeoff_batch_no
     *
     * @param writeoffBatchNo the value for cu_ac_writeoff.writeoff_batch_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setWriteoffBatchNo(String writeoffBatchNo) {
        this.writeoffBatchNo = writeoffBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.remark
     *
     * @return the value of cu_ac_writeoff.remark
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.remark
     *
     * @param remark the value for cu_ac_writeoff.remark
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.create_user_code
     *
     * @return the value of cu_ac_writeoff.create_user_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getCreateUserCode() {
        return createUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.create_user_code
     *
     * @param createUserCode the value for cu_ac_writeoff.create_user_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setCreateUserCode(String createUserCode) {
        this.createUserCode = createUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.create_user_name
     *
     * @return the value of cu_ac_writeoff.create_user_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.create_user_name
     *
     * @param createUserName the value for cu_ac_writeoff.create_user_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.modify_user_code
     *
     * @return the value of cu_ac_writeoff.modify_user_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getModifyUserCode() {
        return modifyUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.modify_user_code
     *
     * @param modifyUserCode the value for cu_ac_writeoff.modify_user_code
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setModifyUserCode(String modifyUserCode) {
        this.modifyUserCode = modifyUserCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.modify_user_name
     *
     * @return the value of cu_ac_writeoff.modify_user_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getModifyUserName() {
        return modifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.modify_user_name
     *
     * @param modifyUserName the value for cu_ac_writeoff.modify_user_name
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setModifyUserName(String modifyUserName) {
        this.modifyUserName = modifyUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.active
     *
     * @return the value of cu_ac_writeoff.active
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.active
     *
     * @param active the value for cu_ac_writeoff.active
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setActive(String active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.is_delete
     *
     * @return the value of cu_ac_writeoff.is_delete
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.is_delete
     *
     * @param isDelete the value for cu_ac_writeoff.is_delete
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.create_date
     *
     * @return the value of cu_ac_writeoff.create_date
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.create_date
     *
     * @param createDate the value for cu_ac_writeoff.create_date
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.modify_date
     *
     * @return the value of cu_ac_writeoff.modify_date
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.modify_date
     *
     * @param modifyDate the value for cu_ac_writeoff.modify_date
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.is_init
     *
     * @return the value of cu_ac_writeoff.is_init
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getIsInit() {
        return isInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.is_init
     *
     * @param isInit the value for cu_ac_writeoff.is_init
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setIsInit(String isInit) {
        this.isInit = isInit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.version_no
     *
     * @return the value of cu_ac_writeoff.version_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public Long getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.version_no
     *
     * @param versionNo the value for cu_ac_writeoff.version_no
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setVersionNo(Long versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.attribute
     *
     * @return the value of cu_ac_writeoff.attribute
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.attribute
     *
     * @param attribute the value for cu_ac_writeoff.attribute
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.option
     *
     * @return the value of cu_ac_writeoff.option
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public Long getOption() {
        return option;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.option
     *
     * @param option the value for cu_ac_writeoff.option
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setOption(Long option) {
        this.option = option;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cu_ac_writeoff.customer_type
     *
     * @return the value of cu_ac_writeoff.customer_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public String getCustomerType() {
        return customerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cu_ac_writeoff.customer_type
     *
     * @param customerType the value for cu_ac_writeoff.customer_type
     *
     * @mbggenerated Thu Feb 23 19:47:58 CST 2017
     */
    public void setCustomerType(String customerType) {
        this.customerType = customerType;
    }
}