package com.self.ddyoung.daily.dao;

import com.self.ddyoung.daily.model.DataDO;
import com.self.ddyoung.daily.model.DataDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int countByExample(DataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int deleteByExample(DataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int insert(DataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int insertSelective(DataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    List<DataDO> selectByExample(DataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    DataDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") DataDO record, @Param("example") DataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int updateByExample(@Param("record") DataDO record, @Param("example") DataDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int updateByPrimaryKeySelective(DataDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int updateByPrimaryKey(DataDO record);
}