package com.self.ddyoung.daily.dao;

import com.pamirs.commons.dao.BaseDAO;
import com.self.ddyoung.daily.model.UserDO;
import com.self.ddyoung.daily.model.UserDOExample;
import java.util.List;

import com.self.ddyoung.daily.model.UserQueryDO;
import org.apache.ibatis.annotations.Param;

public interface UserDAO  extends BaseDAO<UserDO> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int countByExample(UserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int deleteByExample(UserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    List<UserDO> selectByExample(UserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserDO record, @Param("example") UserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int updateByExample(@Param("record") UserDO record, @Param("example") UserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_100w
     *
     * @mbggenerated Fri Mar 10 15:11:34 CST 2017
     */
    int updateByPrimaryKey(UserDO record);
}